[bot]
owner_tg_id = "BOT_OWNER_TG_ID"
token = "BOT_TOKEN"
drop_pending = "BOT_DROP_PENDING"
use_webhook = "BOT_USE_WEBHOOK"
use_class_middlewares = "BOT_USE_CLASS_MIDDLEWARES"
actions_timeout = "BOT_ACTIONS_TIMEOUT"
page_size = "BOT_PAGE_SIZE"

logger.name = "BOT_LOGGER_NAME"
logger.level = "BOT_LOGGER_LEVEL"
logger.stream = "BOT_LOGGER_STREAM"
logger.file_path = "BOT_LOGGER_FILE_PATH"
logger.format = "BOT_LOGGER_FORMAT"

allowed_updates = "BOT_ALLOWED_UPDATES"

state_storage.type = "BOT_STATE_STORAGE_TYPE"
state_storage.redis.host = "BOT_STATE_STORAGE_REDIS_HOST"
state_storage.redis.port = "BOT_STATE_STORAGE_REDIS_PORT"
state_storage.redis.db = "BOT_STATE_STORAGE_REDIS_DB"
state_storage.redis.password = "BOT_STATE_STORAGE_REDIS_PASSWORD"
state_storage.redis.prefix = "BOT_STATE_STORAGE_REDIS_PREFIX"

webhook.url = "BOT_WEBHOOK_URL"
webhook.secret_token = "BOT_WEBHOOK_SECRET_TOKEN"
webhook.cert_path = "BOT_WEBHOOK_CERT_PATH"
webhook.ip_address = "BOT_WEBHOOK_IP_ADDRESS"
webhook.max_connections = "BOT_WEBHOOK_MAX_CONNECTIONS"

telegram_api_url = "BOT_TELEGRAM_API_URL"

[db]
host = "DB_HOST"
port = "DB_PORT"
user = "DB_USER"
password = "DB_PASSWORD"
database = "DB_DATABASE"

logger.name = "DB_LOGGER_NAME"
logger.level = "DB_LOGGER_LEVEL"
logger.stream = "DB_LOGGER_STREAM"
logger.file_path = "DB_LOGGER_FILE_PATH"
logger.format = "DB_LOGGER_FORMAT"

# [extra sections if any]
# ...

[logger]
name = "LOGGER_NAME"
level = "LOGGER_LEVEL"
stream = "LOGGER_STREAM"
file_path = "LOGGER_FILE_PATH"
format = "LOGGER_FORMAT"

[messages]
welcome = "MESSAGES_WELCOME"
unregistered_help = "MESSAGES_UNREGISTERED_HELP"
player_help = "MESSAGES_PLAYER_HELP"
manager_help = "MESSAGES_MANAGER_HELP"
owner_help = "MESSAGES_OWNER_HELP"
anti_flood = "MESSAGES_ANTI_FLOOD"
get_player_name = "MESSAGES_GET_PLAYER_NAME"
invalid_player_name = "MESSAGES_INVALID_PLAYER_NAME"
player_name_already_taken = "MESSAGES_PLAYER_NAME_ALREADY_TAKEN"
player_registered = "MESSAGES_PLAYER_REGISTERED"
player_balance = "MESSAGES_PLAYER_BALANCE"
choose_money_transfer_recipient = "MESSAGES_CHOOSE_MONEY_TRANSFER_RECIPIENT"
choose_new_queue_location = "MESSAGES_CHOOSE_NEW_QUEUE_LOCATION"
new_queue_location_cancelled = "MESSAGES_NEW_QUEUE_LOCATION_CANCELLED"
queue_entry_added = "MESSAGES_QUEUE_ENTRY_ADDED"
player_queue_location = "MESSAGES_PLAYER_QUEUE_LOCATION"
player_left_queue = "MESSAGES_PLAYER_LEFT_QUEUE"
manager_registration_forbidden = "MESSAGES_MANAGER_REGISTRATION_FORBIDDEN"
manager_registration_disabled = "MESSAGES_MANAGER_REGISTRATION_DISABLED"
get_manager_password = "MESSAGES_GET_MANAGER_PASSWORD"
get_manager_name = "MESSAGES_GET_MANAGER_NAME"
invalid_manager_name = "MESSAGES_INVALID_MANAGER_NAME"
manager_name_already_taken = "MESSAGES_MANAGER_NAME_ALREADY_TAKEN"
manager_registered = "MESSAGES_MANAGER_REGISTERED"
add_player_error = "MESSAGES_ADD_PLAYER_ERROR"
player_not_found_error = "MESSAGES_PLAYER_NOT_FOUND_ERROR"
player_not_in_queue_error = "MESSAGES_PLAYER_NOT_IN_QUEUE_ERROR"
queue_entry_already_exists_error = "MESSAGES_QUEUE_ENTRY_ALREADY_EXISTS_ERROR"
add_manager_error = "MESSAGES_ADD_MANAGER_ERROR"
add_user_error = "MESSAGES_ADD_USER_ERROR"
add_tg_account_error = "MESSAGES_ADD_TG_ACCOUNT_ERROR"
unknown_error = "MESSAGES_UNKNOWN_ERROR"

[buttons]
reg_player = "BUTTONS_REG_PLAYER"
reg_manager = "BUTTONS_REG_MANAGER"
new_queue = "BUTTONS_NEW_QUEUE"
my_balance = "BUTTONS_MY_BALANCE"
transfer_money = "BUTTONS_TRANSFER_MONEY"
my_queue = "BUTTONS_MY_QUEUE"
leave_queue = "BUTTONS_LEAVE_QUEUE"
prev_page = "BUTTONS_PREV_PAGE"
next_page = "BUTTONS_NEXT_PAGE"
list_all_players = "BUTTONS_LIST_ALL_PLAYERS"
list_all_locations = "BUTTONS_LIST_ALL_LOCATIONS"
add_balance = "BUTTONS_ADD_BALANCE"
subtract_balance = "BUTTONS_SUBTRACT_BALANCE"
choose_location = "BUTTONS_CHOOSE_LOCATION"
help = "BUTTONS_HELP"
cancel = "BUTTONS_CANCEL"
