[bot]
owner_tg_id = "BOT_OWNER_TG_ID"
token = "BOT_TOKEN"
drop_pending = "BOT_DROP_PENDING"
use_webhook = "BOT_USE_WEBHOOK"
use_class_middlewares = "BOT_USE_CLASS_MIDDLEWARES"
actions_timeout = "BOT_ACTIONS_TIMEOUT"
page_size = "BOT_PAGE_SIZE"

logger.name = "BOT_LOGGER_NAME"
logger.level = "BOT_LOGGER_LEVEL"
logger.stream = "BOT_LOGGER_STREAM"
logger.file_path = "BOT_LOGGER_FILE_PATH"
logger.format = "BOT_LOGGER_FORMAT"

allowed_updates = "BOT_ALLOWED_UPDATES"

state_storage.type = "BOT_STATE_STORAGE_TYPE"
state_storage.redis.host = "BOT_STATE_STORAGE_REDIS_HOST"
state_storage.redis.port = "BOT_STATE_STORAGE_REDIS_PORT"
state_storage.redis.db = "BOT_STATE_STORAGE_REDIS_DB"
state_storage.redis.password = "BOT_STATE_STORAGE_REDIS_PASSWORD"
state_storage.redis.prefix = "BOT_STATE_STORAGE_REDIS_PREFIX"

webhook.url = "BOT_WEBHOOK_URL"
webhook.secret_token = "BOT_WEBHOOK_SECRET_TOKEN"
webhook.cert_path = "BOT_WEBHOOK_CERT_PATH"
webhook.ip_address = "BOT_WEBHOOK_IP_ADDRESS"
webhook.max_connections = "BOT_WEBHOOK_MAX_CONNECTIONS"

telegram_api_url = "BOT_TELEGRAM_API_URL"

[db]
host = "DB_HOST"
port = "DB_PORT"
user = "DB_USER"
password = "DB_PASSWORD"
database = "DB_DATABASE"

logger.name = "DB_LOGGER_NAME"
logger.level = "DB_LOGGER_LEVEL"
logger.stream = "DB_LOGGER_STREAM"
logger.file_path = "DB_LOGGER_FILE_PATH"
logger.format = "DB_LOGGER_FORMAT"

# [extra sections if any]
# ...

[logger]
name = "LOGGER_NAME"
level = "LOGGER_LEVEL"
stream = "LOGGER_STREAM"
file_path = "LOGGER_FILE_PATH"
format = "LOGGER_FORMAT"

[messages]
welcome = "MESSAGES_WELCOME"
unregistered_help = "MESSAGES_UNREGISTERED_HELP"
player_help = "MESSAGES_PLAYER_HELP"
manager_help = "MESSAGES_MANAGER_HELP"
owner_help = "MESSAGES_OWNER_HELP"
anti_flood = "MESSAGES_ANTI_FLOOD"
get_player_name = "MESSAGES_GET_PLAYER_NAME"
invalid_player_name = "MESSAGES_INVALID_PLAYER_NAME"
player_name_already_taken = "MESSAGES_PLAYER_NAME_ALREADY_TAKEN"
player_registered = "MESSAGES_PLAYER_REGISTERED"
add_player_error = "MESSAGES_ADD_PLAYER_ERROR"
add_tg_account_error = "MESSAGES_ADD_TG_ACCOUNT_ERROR"
unknown_error = "MESSAGES_UNKNOWN_ERROR"

[buttons]
reg_player = "BUTTONS_REG_PLAYER"
reg_manager = "BUTTONS_REG_MANAGER"
new_queue = "BUTTONS_NEW_QUEUE"
my_balance = "BUTTONS_MY_BALANCE"
transfer_money = "BUTTONS_TRANSFER_MONEY"
help = "BUTTONS_HELP"
cancel = "BUTTONS_CANCEL"
