[bot]
owner_tg_id = 123456789
token = "token"
drop_pending = true
use_webhook = false
use_class_middlewares = true
actions_timeout = 0.2
page_size = 10

logger.name = "BotLogger"
logger.level = "INFO"
logger.stream = "stdout"
logger.file_path = "logs/bot.log"
logger.format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# allowed_updates = [...] or "ALL"

state_storage.type = "redis"
state_storage.redis.host = "localhost"
state_storage.redis.port = 6379
# state_storage.redis.db = 0
# state_storage.redis.password = "password"
# state_storage.redis.prefix = "prefix"

webhook.url = "webhook_url"
webhook.secret_token = "secret token"
# webhook.cert_path = "cert_path"
# webhook.ip_address = "ip_address"
# webhook.max_connections = 40

# telegram_api_url = "telegram_api_url"

[db]
host = "localhost"
port = 5432
user = "user"
password = "password"
database = "database"

logger.name = "DBLogger"
logger.level = "INFO"
logger.stream = "stdout"
logger.file_path = "logs/db.log"
logger.format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# [extra sections if any]
# ...

[logger]
name = "FairLogger"
level = "INFO"
stream = "stdout"
file_path = "logs/fair.log"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[messages]
welcome = "Welcome"
unregistered_help = "Unregistered help"
player_help = "Player help"
manager_help = "Manager help"
anti_flood = "Anti flood"
choose_location_cancelled = "Choose location cancelled"
location_updated = "Location updated"
chosen_location = "Chosen location"
my_location_queue = "My location queue"
my_location_queue_cancelled = "My location queue cancelled"
location_player_chosen_options = "Location player chosen options"
location_paused = "Location paused"
location_unpaused = "Location unpaused"
bad_location_error = "Bad location error"
pause_location_error = "Pause location error"
unpause_location_error = "Unpause location error"
unknown_error = "Unknown error"

[buttons]
reg_player = "Register as player"
reg_manager = "Register as manager"
choose_location = "Choose location"
my_location = "My location"
leave_location = "Leave location"
my_location_queue = "My location queue"
reward_player = "Reward player"
purchase = "Purchase"
pause_location = "Pause location"
unpause_location = "Unpause location"
prev_page = "<<"
next_page = ">>"
help = "Help"
cancel = "Cancel"
