[bot]
owner_tg_id = 123456789
token = "token"
drop_pending = true
use_webhook = false
use_class_middlewares = true
actions_timeout = 0.2

logger.name = "BotLogger"
logger.level = "INFO"
logger.stream = "stdout"
logger.file_path = "logs/bot.log"
logger.format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# allowed_updates = [...] or "ALL"

state_storage.type = "redis"
state_storage.redis.host = "localhost"
state_storage.redis.port = 6379
# state_storage.redis.db = 0
# state_storage.redis.password = "password"
# state_storage.redis.prefix = "prefix"

webhook.url = "webhook_url"
webhook.secret_token = "secret token"
# webhook.cert_path = "cert_path"
# webhook.ip_address = "ip_address"
# webhook.max_connections = 40

# telegram_api_url = "telegram_api_url"

[db]
host = "localhost"
port = 5432
user = "user"
password = "password"
database = "database"

logger.name = "DBLogger"
logger.level = "INFO"
logger.stream = "stdout"
logger.file_path = "logs/db.log"
logger.format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# [extra sections if any]
# ...

[logger]
name = "FairLogger"
level = "INFO"
stream = "stdout"
file_path = "logs/fair.log"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[messages]
welcome = "Welcome"
unregistered_help = "Unregistered help"
player_help = "Player help"
manager_help = "Manager help"
anti_flood = "Anti flood"
manager_registration_forbidden = "Manager registration forbidden"
manager_registration_disabled = "Manager registration disabled"
get_manager_password = "Get manager password"
get_manager_name = "Get manager name"
invalid_manager_name = "Invalid manager name"
manager_name_already_taken = "Manager name already taken"
add_manager_error = "Add manager error"
manager_registered = "Manager registered"
unknown_error = "Unknown error"

[buttons]
reg_player = "Register as player"
reg_manager = "Register as manager"
list_all_players = "List all players"
list_all_locations = "List all locations"
add_balance = "Add balance"
subtract_balance = "Subtract balance"
choose_location = "Choose location"
help = "Help"
cancel = "Cancel"
